  quarkus.datasource.db-kind=postgresql
  quarkus.datasource.username=${DB_USERNAME:webhookuser}
  quarkus.datasource.password=${DB_PASSWORD:webhookpass}
  quarkus.datasource.jdbc.url=${DB_URL:jdbc:postgresql://localhost:5432/webhookdb}

  quarkus.flyway.migrate-at-start=true
  quarkus.hibernate-orm.database.generation=none

  kafka.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

  mp.messaging.outgoing.platform-events-out.connector=smallrye-kafka
  mp.messaging.outgoing.platform-events-out.topic=platform-events
  mp.messaging.outgoing.platform-events-out.value.serializer=org.apache.kafka.common.serialization.StringSerializer

  mp.messaging.incoming.platform-events-in.connector=smallrye-kafka
  mp.messaging.incoming.platform-events-in.topic=platform-events
  mp.messaging.incoming.platform-events-in.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
  mp.messaging.incoming.platform-events-in.auto.offset.reset=earliest
  mp.messaging.incoming.platform-events-in.group.id=webhook-dispatcher

  mp.jwt.verify.publickey=${JWT_PUBLIC_KEY}
  smallrye.jwt.sign.key=${JWT_PRIVATE_KEY}
  mp.jwt.verify.issuer=webhook-dispatch-system
  quarkus.smallrye-jwt.enabled=true

  internal.token=${INTERNAL_TOKEN:change-me-secret}
  quarkus.log.level=INFO
